### ISSUE TITLE
Table border spacing

### ISSUE THREAD

**Issue by samyex6** [catmanjan/anutimetable#51]
Do you think the table will look better after adding border-space?

```css
.table {
    border-collapse: separate;
    border-spacing: 2px;
}
```
